##### Menu
menu:
  Home: /
  Archives: /archives
  About: /about
## you can create `tags` and `categories` folders in `../source`.
## And create a `index.md` file in each of them.
## set `front-matter`as
## layout: tags (or categories)
## title: tags (or categories)
## ---

#### Widgets
widgets: 
- category
- tag
- links
- weibo
- blogroll
- rss
## provide seven widgets:category,tag,rss,archive,tagcloud,links,weibo
## modify links in `/layout/_widget/links.ejs`.

#### RSS 
rss: ## RSS address.

#### Image
imglogo:
  enable: true             ## display image logo true/false.
  src: img/logo.png        ## `.svg` and `.png` are recommended,please put image into the theme folder `/jacman/source/img`.
favicon: img/favicon.ico   ## size:32px*32px,`.ico` is recommended,please put image into the theme folder `/jacman/source/img`.     
apple_icon: img/jacman.jpg ## size:114px*114px,please put image into the theme folder `/jacman/source/img`.
author_img: img/author.jpg ## size:220px*220px.display author avatar picture.if don't want to display,please don't set this.

#### index post is expanding or not 
index:
  expand: false           ## default is unexpanding,so you can only see the short description of each post.
  excerpt_link: Read More  
  
#### Author information
author:
  intro_line1:  Where there is a will, there is a way!
  intro_line2:  有智者事竟成！
  weibo:      zhangyouzhi
  weibo_verifier:  4a0b79d5
  tsina:      1805858587
  douban:     ## e.g. zhangyouzhi or your id for https://www.douban.com/people/zhangyouzhi
  zhihu:      ## e.g. jark  for http://www.zhihu.com/people/zhangyouzhi
  email:      ## e.g. iamzhangyouzhi@gmail.com
  twitter:    zhangyouzhi
  github:     ## e.g. wuchong for https://github.com/zhangyouzhi
  facebook:   zhangyouzhi
  linkedin:   in/zhangyouzhi
  google_plus:    ## e.g. "111190881341800841449" for https://plus.google.com/u/0/111190881341800841449, the "" is needed!
  stackoverflow:  ## e.g. 3180133 for http://stackoverflow.com/users/3180133/zhangyouzhi
## if you set them, the corresponding  share button will show on the footer

#### Toc
toc:
  article: true   ## show contents in article.
  aside: true     ## show contents in aside.
## you can set both of the value to true of neither of them.
## if you don't want display contents in a specified post,you can modify `front-matter` and add `toc: false`.

#### Links
links:
  ZhangYouzhi's Blog: http://zhangyouzhi.com
  CSDN: http://blog.csdn.net/iamzhangyouzhi
  

#### Comment
duoshuo_shortname: zhangyouzhi
disqus_shortname:  ## e.g. zhagyouzhi   your disqus short name.

#### Share button
jiathis:
  enable: false ## if you use jiathis as your share tool,the built-in share tool won't be display.
  id:    ## e.g. 1889330 your jiathis ID. 
  tsina: ## e.g. 2176287895 Your weibo id,It will be used in share button.
  
#### Analytics
google_analytics:
  enable: false
  id:        ## e.g. UA-60193180-1 your google analytics ID.
  site:      ## e.g. zhangyouzhi.com your google analytics site or set the value as auto.
## You MUST upgrade to Universal Analytics first!
## https://developers.google.com/analytics/devguides/collection/upgrade/?hl=zh_CN
baidu_tongji:
  enable: false
  sitecode:  61fb52aed126ee3e365a04e1624aeb45 ## e.g. 61fb52aed126ee3e365a04e1624aeb45 your baidu tongji site code
cnzz_tongji:
  enable: false
  siteid:    ## e.g. 1253575964 your cnzz tongji site id

#### Miscellaneous
ShowCustomFont: true  ## you can change custom font in `variable.styl` and `font.styl` which in the theme folder `/jacman/source/css`.
fancybox: true        ## if you use gallery post or want use fancybox please set the value to true.
totop: true           ## if you want to scroll to top in every post set the value to true


#### Custom Search
google_cse: 
  enable: false
  cx:   ## e.g. 018294693190868310296:abnhpuysycw your Custom Search ID.
## https://www.google.com/cse/ 
## To enable the custom search You must create a "search" folder in '/source' and a "index.md" file
## set the 'front-matter' as
## layout: search 
## title: search
## ---
baidu_search:     ## http://zn.baidu.com/
  enable: false
  id:   61fb52aed126ee3e365a04e1624aeb45 ## e.g. "61fb52aed126ee3e365a04e1624aeb45"  for your baidu search id
  site: http://zhangyouzhi.com  ## your can change to your site instead of the default site
  
